name: GBPayUsers
description: "GBPay Users"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  localstorage: ^5.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.4.0+2
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  printing: ^5.12.0
  barcode_widget: ^2.0.4
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/auth/
    - assets/images/home/arslan.jpg
    - assets/images/police/
    - assets/lottie/
    - assets/icons/
    - assets/images/card/
